# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/remind101/pkg
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - restore_cache:
          keys:
            - dynamodb-installed
      - run:
          name: Install Java
          command: 'sudo apt-get update && sudo apt-get install default-jre default-jdk'
      - run:
          name: Setup Container
          command: |
              test -f DynamoDBLocal.jar || curl -k -L -o dynamodb-local.tgz http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
              test -f DynamoDBLocal.jar || tar -xzf dynamodb-local.tgz
      - save_cache:
          key: dynamodb-installed
          paths:
            - DynamoDBLocal_lib
            - DynamoDBLocal.jar
      - run:
          name: Launch Dynamodb
          command: java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
          background: true
      - run: make deps
      - run: go get -v -t -d ./...
      - run:
          name: Run Tests
          command: go test ./...
          environment:
            AWS_ACCESS_KEY_ID: DUMMY_KEY
            AWS_SECRET_ACCESS_KEY: DUMMY_SECRET
