version: 2.1

workflows:
  main:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: go vet ./...
      - run: go test ./...
