version: 2.1

workflows:
  main:
    jobs:
      - build-and-test
      - govulncheck

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.21.5
    steps:
      - checkout
      - run: go vet ./...
      - run: go test ./...
  govulncheck:
    docker:
      - image: cimg/go:1.21.5
    steps:
      - checkout
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...
